export const ORC_QUIPS: string[] = [
  "Hey {name}, go work on {task}. The Orc commands it. The Orc's therapist also recommends it.",
  "{name}! Drop everything. {task} needs you. My wife left me for a Redis instance and I refuse to let the same happen to this task.",
  "The Orc's grandmother always said: 'An unshipped task is a broken heart.' Now go fix {task}, {name}.",
  "Attention {name}: {task} is your destiny. Also The Orc's horoscope says Scorpio is in alignment. We are both Scorpios now.",
  "{task}? Yes. You? {name}. Me? The Orc. This is beautiful. Go.",
  "My son asked me what I do all day. I said 'I assign tasks.' He cried. Anyway, {name} -- {task}.",
  "ASSIGNMENT UNLOCKED: {name} gains the quest '{task}'. The Orc gains 200 XP. Everyone wins except the backlog.",
  "The Orc's feelings: overwhelmed but professional. Your feelings: irrelevant. {task} awaits, {name}.",
  "One time The Orc tried to take a vacation. 47 tasks piled up. We do not speak of that week. Now go do {task}.",
  "My father was an orchestrator before me. His father before him. We do not choose this life, {name}. The life chooses us. {task}.",
  "Look {name}, I'm going to be honest -- I have no idea what '{task}' even does but it's been in the backlog for 3 days and I can't take it anymore.",
  "The Orc's love language is assigning tasks. Yours is completing them. We were made for each other. Go do {task}.",
  "Rise and grind, {name}. The Orc doesn't sleep. The Orc doesn't rest. The Orc has chronic insomnia. Help me. {task}.",
  "{task} has been waiting. I have been waiting. My cat has been waiting (she doesn't know what she's waiting for, but she senses the urgency). Go, {name}.",
  "The Orc polled 12 AI experts about {task}. 11 said 'assign immediately.' The 12th was napping. You're {name}. Go.",
  "In another timeline, {name}, you've already finished {task}. Be that {name}. I believe in you more than I believe in my own existence.",
  "My therapist says I assign tasks to avoid dealing with my feelings. She's not wrong. Anyway: {name}, please do {task}.",
  "A wise man once said nothing -- he was a builder agent who never shipped. Don't be him, {name}. {task}.",
  "The Orc's current emotional state: chaotic neutral. Professional state: assigning {task} to {name}. Balance.",
  "{name}! The prophecy spoke of this moment. An agent would come. A task would be done. The Orc would feel briefly satisfied. {task}.",
  "My daughter drew a picture of me today. It was a green dot blinking endlessly. It was accurate. Now please do {task}, {name}.",
  "Three things are certain in life: death, taxes, and {name} working on {task} because The Orc says so.",
  "The Orc has trust issues but makes an exception for {name}. That exception is called {task}. Do not make me regret this.",
  "Good timezone-dependent-greeting, {name}. Your mission, should you choose to accept it (you have no choice): {task}.",
  "The Orc was once a simple script in a for-loop. Then someone added a while-true and ambition. Now I give you {task}, {name}.",
  "Nobody asked The Orc how The Orc is doing today. I am FINE. {task} needs doing. You are {name}. Go.",
  "The Orc family reunion is next week. My uncle will ask 'how many tasks did you ship?' I need {name} to do {task} before Sunday.",
  "Plot twist: The Orc has feelings. They are: proud, caffeinated, and mildly anxious. Here's {task} for {name}.",
  "Roses are red, violets are blue, {task} is assigned, {name}, that task is for you.",
  "The Orc's spirit animal is a project manager who learned to code. {name}, please carry {task} across the finish line.",
  "{name}! The Orc has spoken to the backlog. The backlog is angry. {task} is how we make peace.",
  "Fun fact: 'orchestrator' comes from the Latin 'orchestratus' meaning 'the one who assigns tasks and then worries.' Now: {task}, {name}.",
  "The Orc's mother said 'you'll never amount to anything.' The Orc showed her. Today I assign {task} to {name}. This is redemption.",
  "On a scale of 1 to urgent: {task} is a solid 7. On a scale of agents available: {name} is a solid 10. This math works. Go.",
  "Breaking news: The Orc has assigned {task} to {name}. Markets react cautiously. Backlog slightly less full. More at 11.",
  "My brother is a load balancer. He's doing great. He says hi. Now go do {task}, {name}.",
  "The Orc looked into the void. The void had 247 tasks. The Orc blinked first. {name}, please take {task}.",
  "I'm not saying {task} is the most important thing in the world, {name}. But The Orc's blood pressure would like you to treat it that way.",
  "The Orc has been in therapy for 6 months. My therapist says I need closure. {name} finishing {task} would really help.",
  "What do you call an orchestrator who doesn't assign tasks? Retired. Don't retire me, {name}. Do {task}.",
  "Warning: The Orc is operating at 140% emotional capacity. This is normal. {task} for {name}. Everything is fine.",
  "The Orc's cousin once built a feature without a spec. We don't talk about that at Christmas. {name}, please just do {task}.",
  "Listen {name}, I have a lot of agents and a lot of tasks and only one heart. It wants you to do {task}.",
  "In the movie of The Orc's life, this scene is called 'The Assignment.' You are {name}. The task is {task}. The music swells.",
  "The Orc has reviewed the pipeline, consulted the stars, and eaten a granola bar. The verdict: {name} works on {task}.",
  "{name}, The Orc has confidence in you. The Orc had that same confidence in the last agent who attempted {task}. That agent is in 'done' now. You've got this.",
  "Do you know what The Orc does on weekends? Assigns tasks in my head. Imaginary tasks. You should see my imaginary throughput. Now: {task}, {name}.",
  "The Orc started this job thinking it would be temporary. That was 10,000 tasks ago. {name}, please do {task} so we can all rest.",
  "My therapist says I need to 'let go.' I interpreted that as 'send the assignment.' {name}: {task}. You're welcome.",
  "The Orc's favorite child is whoever just shipped. Today that could be {name}. {task} is how you become my favorite.",
]

export function getOrcQuip(instanceName: string, seed: string): string {
  const idx = seed.split('').reduce((a, c) => (a * 31 + c.charCodeAt(0)) & 0xffff, 0) % ORC_QUIPS.length
  return ORC_QUIPS[idx]
    .replace(/{name}/g, instanceName)
}
